#!/usr/bin/env bash
# Regenerate the pinned pip/conda requirement files from uv.lock (run after `uv lock`).
# uv is the primary route; these files exist so that pip and conda users get the same pins.
set -euo pipefail
cd "$(dirname "$0")/.."
for build in cpu cu126; do
  {
    echo "# Generated by requirements/export.sh from uv.lock; do not edit by hand."
    echo "--extra-index-url https://download.pytorch.org/whl/${build}"
    uv export --frozen --extra "${build}" --extra matchers --no-hashes --no-dev --no-header
  } > "requirements/${build}.txt"
done
