#!/usr/bin/env bash
# Regenerate the pinned pip/conda requirement files from uv.lock (run after `uv lock`).
# uv is the primary route; these files exist so that pip and conda users get the same pins.
set -euo pipefail
cd "$(dirname "$0")/.."
for build in cpu cu126; do
  {
    echo "# Generated by requirements/export.sh from uv.lock; do not edit by hand."
    echo "--extra-index-url https://download.pytorch.org/whl/${build}"
    uv export --frozen --extra "${build}" --extra matchers --extra train --no-hashes --no-dev --no-header
  } > "requirements/${build}.txt"
done

# The Hugging Face Space (space/): the evaluation pins (matchers extra, no train extra, no project),
# with torch/torchvision from the CUDA 12.8 index, which has kernels for ZeroGPU's Blackwell GPUs (same
# 2.8.0 / 0.23.0 versions; the cu126 build has none). The NVIDIA wheels are left to pip so they match that
# torch build. vismatch is left out: plain pip would install its `uniception` dependency, which uv
# suppresses, so the Space installs vismatch and SAM 3 with --no-deps at start-up (space/app.py). SAM 3's
# own imports (iopath, ftfy, decord) are added here. Gradio comes from the Space's sdk_version.
{
  echo "# Generated by requirements/export.sh from uv.lock; do not edit by hand."
  echo "--extra-index-url https://download.pytorch.org/whl/cu128"
  uv export --frozen --extra cu126 --extra matchers --no-hashes --no-dev --no-header --no-emit-project \
    | grep -v '^ *#' | grep -vE '^(nvidia-|vismatch @|uniception|wadler-lindig)' \
    | sed -E 's/^(torch|torchvision)==([0-9.]+)\+cu126/\1==\2+cu128/'
  printf '%s\n' "iopath==0.1.10" "ftfy==6.1.1" "portalocker==4.4.0" "wcwidth==0.9.2" "decord==0.6.0"
} > space/requirements.txt
