#!/usr/bin/env bash
# Regenerate the pinned pip/conda requirement files from uv.lock (run after `uv lock`).
# uv is the primary route; these files exist so that pip and conda users get the same pins.
set -euo pipefail
cd "$(dirname "$0")/.."
for build in cpu cu126; do
  {
    echo "# Generated by requirements/export.sh from uv.lock; do not edit by hand."
    echo "--extra-index-url https://download.pytorch.org/whl/${build}"
    uv export --frozen --extra "${build}" --extra matchers --extra train --no-hashes --no-dev --no-header
  } > "requirements/${build}.txt"
done

# The Hugging Face Space (space/): the evaluation pins (matchers extra, no train extra, no project), with
# torch/torchvision as plain 2.8.0 / 0.23.0 pins: ZeroGPU accepts only plain supported versions (it rejected
# `+cu128`, 2026-10-10), and the PyPI Linux wheels of 2.8.0 are the CUDA 12.8 build, which has kernels for
# ZeroGPU's Blackwell GPUs (the cu126 build has none). The NVIDIA wheels are left to pip so they match it.
# Git-only packages go to space/no_deps.txt instead, which space/app.py installs with --no-deps at start-up:
# pip cannot reconcile glue-factory's unpinned LightGlue URL with the pinned commit (the Space build failed on
# it), and with dependencies it would add vismatch's `uniception` (suppressed by uv) and SAM 3's numpy<2 pin
# (SAM 3 runs on numpy 2). Their dependencies are all pinned in requirements.txt. SAM 3's own imports (iopath,
# ftfy, decord) are added here. Gradio comes from the Space's sdk_version.
SAM3="sam3 @ git+https://github.com/facebookresearch/sam3.git@f6e51f59500a87c576c2df2323ce56b9fd7a12de"
space_pins=$(uv export --frozen --extra cu126 --extra matchers --no-hashes --no-dev --no-header --no-emit-project \
  | grep -v '^ *#' | grep -vE '^(nvidia-|uniception|wadler-lindig)' \
  | sed -E 's/^(torch|torchvision)==([0-9.]+)\+cu126/\1==\2/')
# The Space build installs requirements.txt together with gradio[oauth,mcp] at the card's sdk_version and the
# `spaces` package, so the pins are resolved with that stack (Linux, Python 3.12); pins it conflicts with and
# that no result depends on are left to the resolver (pydantic: gradio's mcp extra needs <= 2.12.5, the lock has
# 2.13.5; the first build failed on it). gradio and spaces themselves are left out; the build adds them.
GRADIO=$(sed -n 's/^sdk_version: *//p' space/README.md)
SOFT='^(pydantic|pydantic-core)=='
tmp=$(mktemp -d)
{
  echo "$space_pins" | grep -v ' @ git+' | grep -vE "$SOFT"
  # SAM 3's imports beyond the evaluation pins; it also imports psutil and pkg_resources (setuptools < 81), which
  # the evaluation environment has from other packages (the third Space build failed on psutil).
  printf '%s\n' "iopath==0.1.10" "ftfy==6.1.1" "portalocker==4.4.0" "wcwidth==0.9.2" "decord==0.6.0" \
    "psutil==7.2.2" "setuptools==80.10.2"
} > "$tmp/pins.txt"
printf '%s\n' "gradio[oauth,mcp]==${GRADIO}" "spaces" "uvicorn>=0.14.0" "websockets>=10.4" > "$tmp/hub.txt"
uv pip compile "$tmp/pins.txt" "$tmp/hub.txt" --python-version 3.12 --python-platform x86_64-manylinux_2_28 \
  --no-header --no-annotate -q -o "$tmp/resolved.txt"
{
  echo "# Generated by requirements/export.sh from uv.lock; do not edit by hand."
  grep -vE '^(gradio|spaces)==' "$tmp/resolved.txt"
} > space/requirements.txt
rm -rf "$tmp"
{
  echo "# Generated by requirements/export.sh; installed with --no-deps by app.py (see requirements/export.sh)."
  echo "$space_pins" | grep ' @ git+' | sed 's/ *;.*//'
  echo "$SAM3"
} > space/no_deps.txt
